package com.kpihx_labs.myway.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class FrequentItinaryAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFrequentItinaryAllPropertiesEquals(FrequentItinary expected, FrequentItinary actual) {
        assertFrequentItinaryAutoGeneratedPropertiesEquals(expected, actual);
        assertFrequentItinaryAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFrequentItinaryAllUpdatablePropertiesEquals(FrequentItinary expected, FrequentItinary actual) {
        assertFrequentItinaryUpdatableFieldsEquals(expected, actual);
        assertFrequentItinaryUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFrequentItinaryAutoGeneratedPropertiesEquals(FrequentItinary expected, FrequentItinary actual) {
        assertThat(expected)
            .as("Verify FrequentItinary auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFrequentItinaryUpdatableFieldsEquals(FrequentItinary expected, FrequentItinary actual) {
        assertThat(expected)
            .as("Verify FrequentItinary relevant properties")
            .satisfies(e -> assertThat(e.getName()).as("check name").isEqualTo(actual.getName()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFrequentItinaryUpdatableRelationshipsEquals(FrequentItinary expected, FrequentItinary actual) {}
}
