package com.myway.myway.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class PlaceCategoryAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPlaceCategoryAllPropertiesEquals(PlaceCategory expected, PlaceCategory actual) {
        assertPlaceCategoryAutoGeneratedPropertiesEquals(expected, actual);
        assertPlaceCategoryAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPlaceCategoryAllUpdatablePropertiesEquals(PlaceCategory expected, PlaceCategory actual) {
        assertPlaceCategoryUpdatableFieldsEquals(expected, actual);
        assertPlaceCategoryUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPlaceCategoryAutoGeneratedPropertiesEquals(PlaceCategory expected, PlaceCategory actual) {
        assertThat(expected)
            .as("Verify PlaceCategory auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPlaceCategoryUpdatableFieldsEquals(PlaceCategory expected, PlaceCategory actual) {
        assertThat(expected)
            .as("Verify PlaceCategory relevant properties")
            .satisfies(e -> assertThat(e.getName()).as("check name").isEqualTo(actual.getName()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPlaceCategoryUpdatableRelationshipsEquals(PlaceCategory expected, PlaceCategory actual) {}
}
